services:
  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL:?err}
      - DATASOURCE_USER=${DATASOURCE_USER:?err}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD:?err}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID:?err}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET:?err}
      - FRONTEND_URL=${FRONTEND_URL:?err}
      - JWT_SECRET=${JWT_SECRET:?err}
      - JWT_EXPIRY=${JWT_EXPIRY:?err}

  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    ports:
      - "80:80"